on: [push]

jobs:
  typechecking:
    runs-on: ubuntu-latest
    name: A job to typecheck Agda code
    steps:
    - name: "Clone repository"
      uses: actions/checkout@v2
    - name: Typecheck
      id: typecheck
      uses: ayberkt/agda-github-action@latest
      with:
        main-file: Main.lagda.md
        source-dir: FormalTopology
    - run: pwd
    - run: ls
    - run: sudo cp -f resources/Agda.css FormalTopology/html/Agda.css
    - name: Upload HTML
      id: html-upload
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v1
      with:
        name: html
        path: FormalTopology/html
    - name: Deploy to GitHub Pages
      id: deploy
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: FormalTopology/html